### ISSUE TITLE
Versions du schéma 

### ISSUE THREAD

**Issue by johanricher** [PnX-SI/schema_randonnee#2]
Votre dépôt Git doit comporter des tags indiquant les versions de votre schéma. Ces versions doivent respecter [la gestion sémantique de version semver](https://semver.org/lang/fr/).

Ainsi, les URL déclarées dans schéma comme `path` ou encore `resources` pourront utiliser un tag Git et ainsi pointer sur la bonne version du schéma ou de la ressource.

Plus d'informations ici : https://schema.data.gouv.fr/documentation/validation-schemas

La documentation SCDL comporte également des précisions utiles à ce sujet : https://scdl.opendatafrance.net/docs/CONTRIBUTING.html

Exemple dans le schéma IRVE : https://github.com/etalab/schema-irve/blob/v1.0.3/schema.json#L8

```
    "path": "https://github.com/etalab/schema-irve/raw/v1.0.3/schema.json",
```

**Comment by camillemonchicourt** [comment]
Oui en effet.
Pour le moment on n'a pas encore valider collectivement de version 0, c'est pourquoi on ne veut pas encore publier une version tant que le collectif ne s'est pas exprimé sur la version 0 que nous leur proposerons dans les prochains jours.

**Comment by johanricher** [comment]
Le schéma peut tout à fait avoir connaître différents numéros de version pendant qu'il est encore en chantier et avant une quelconque "validation" et publication officielle. C'est même une bonne pratique que vous avez commencé à suivre puisque votre schéma comporte déjà un numéro de version (`0.1.2`), il ne manquerait donc pas grand chose pour aller jusqu'au bout.

**Comment by IdrissaD** [comment]
Merci pour la remarque, j'ai créé le tag correspondant. C'est la première fois que je touche à ces fonctiones tag/release, qui plus est en ligne de commande, donc n'hésitez pas à le dire si il reste quelque chose à modifier à ce sujet !

**Comment by johanricher** [comment]
C'est parfait, merci pour ces ajouts !
