### ISSUE TITLE
Inutilité des schémas externes GeoJSON Point et MultiLineString

### ISSUE THREAD

**Issue by IdrissaD** [PnX-SI/schema_randonnee#6]
Le schéma externe `https://geojson.org/schema/Point.json` était utilisé pour la géométrie du parking. Étant donné qu'elle est finalement en WKT, il est inutile et devrait être supprimé  du schéma.

Le schéma externe `https://geojson.org/schema/MultiLineString.json` est utilisé pour la géométrie de l'itinéraire de randonnée. Il s'agissait de laisser une marge d'erreur et de valider un itinéraire si sa géométrie n'était pas une ``LineString``, mais peut-être une ``MultiLineString`` pas fusionnée, ou autre possibilité. La suppression du schéma ``Point`` m'a amené à réévaluer cette marge d'erreur : est-elle souhaitable en termes de qualité des données ?
Le but du schéma étant de garantir une certaine qualité et interopérabilité des données, il est un peu contradictoire de laisser la possibilité d'avoir la géométrie d'un itinéraire en ``MultiLineString``. Y aurait-il des cas où cela serait pertinent de laisser passer une géométrie de ce type ?

**Comment by IdrissaD** [comment]
Je réouvre ce ticket car je pense toujours que c'est inutile de conserver ce schéma externe ``MultiLineString`, et que ça amène plus de contraintes.

 - Le but du schéma étant de garantir une certaine qualité et interopérabilité des données, il est un peu contradictoire de laisser la possibilité d'avoir la géométrie d'un itinéraire en `MultiLineString` ;
 - Le fait d'avoir un schéma externe n'est pas pris en charge par la plupart des implémentations du JSON Schema, et nous limite à une seule librairie (Ajv) et un seul language (JavaScript) pour la validation ;
 - cela a aussi nécessité la création d'une GitHub Action pour la validation sur GitHub (https://github.com/PnX-SI/jsonschema_validator), à maintenir en parallèle du schéma, alors que l'absence de schéma externe permettrait de se reposer sur des GitHub Actions éprouvées et maintenues par la communauté ;
 - la nécessité d'installer Node.js pour faire fonctionner le validateur Ajv est un obstacle technique en plus à l'adoption des chaînes d'export  automatisées. Dans le cadre d'un export depuis Geotrek, le passage à un schéma sans références externes permettrait d'utiliser des implémentations en Python afin d'éviter la multiplication des langages.

**Comment by camillemonchicourt** [comment]
Oui je partage.
Je ne vois pas de raison que les itinéraires soient des multilinestring.

**Comment by amandine-sahl** [comment]
fix by #30
